baseURL = 'https://esp3d.io'
languageCode = 'en-us'
title = 'ESP3D Project'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
themeVariant = "blue"
description = "Web site of ESP3D ecosystem"
disableLandingPageButton = true

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/luc-github/esp3d.io"
weight = 10
